INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Health & Beauty', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Groceries', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tools', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Outdoors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Fitness', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Crafts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Stationery', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kitchen', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Travel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Photography', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bags & Accessories', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Footwear', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Digital Products', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Gifts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Software', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Art', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Collectibles', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Wine & Spirits', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Luxury', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Perfumes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cosmetics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Lighting', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bedding', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hardware', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bathroom Accessories', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Medical Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Safety Gear', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Automotive Accessories', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Smart Home Devices', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Camping', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Marine', NOW());
